[build-system]
requires = [
    "scikit-build-core>=0.10",
    "swig",
    "numpy",
]
build-backend = "scikit_build_core.build"

[project]
name = "ezc3d"
dynamic = ["version"]
dependencies = [
    "numpy",
]
description = "Easy to use C3D reader/writer for C++, Python, and Matlab"
readme = "README.md"  # This links to your README file
authors = [
    {name = "Michaud, Benjamin"},
    {name = "Begon, Mickaël"}
]
license-files = ["LICENSE"]
urls = { "Homepage" = "https://github.com/pyomeca/ezc3d" }
requires-python = ">=3.10"

[[tool.dynamic-metadata]]
provider = "scikit_build_core.metadata.regex"
field = "version"
input = "CMakeLists.txt"
regex = "project\\(ezc3d VERSION (?P<value>\\d+\\.\\d+\\.\\d+)\\)"

[tool.scikit-build]
cmake.args = [
    "-DBUILD_EXAMPLE:BOOL=OFF",
    "-DBINDER_PYTHON3:BOOL=ON",
    "-DCMAKE_INSTALL_BINDIR=ezc3d",
    "-DCMAKE_INSTALL_LIBDIR=ezc3d",
]
wheel.packages = ["ezc3d"]
install.components = ["Unspecified"]

[tool.cibuildwheel]
build-frontend = "build"
