name: Run the tests

on: [pull_request]

env:
  BUILD_FOLDER: build
  EXAMPLES_FOLDER: examples

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/ezc3d
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/ezc3d
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\ezc3d
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: ezc3d
          environment-file: environment.yml
        
      - name: Print mamba info
        run: | 
          mamba config --show
          mamba info
          mamba list
          
      - name: Install extra common dependencies
        run: | 
          mamba install cmake git pkgconfig swig numpy pytest -cconda-forge
          mamba list
          git submodule update --init --recursive

      - name: Build ezc3d UNIX
        run: |
          MAIN_FOLDER=`pwd`
          echo ${{ matrix.prefix }}
          CONDA_ENV_PATH=$CONDA/envs/ezc3d
          mkdir -p $MAIN_FOLDER/$BUILD_FOLDER
          cd $MAIN_FOLDER/$BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_DOC=OFF -DBUILD_EXAMPLE=ON -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_OCTAVE=OFF -DBINDER_PYTHON3=ON ..
          make install -j${{ steps.cpu-cores.outputs.count }}
          cd $MAIN_FOLDER
        if: matrix.label != 'win-64'
       
      - name: Run tests UNIX
        run: |
          MAIN_FOLDER=`pwd`
          cd $MAIN_FOLDER/$BUILD_FOLDER/test
          ./ezc3d_test
          cd $MAIN_FOLDER
        if: matrix.label != 'win-64'
  
      - name: Build ezc3d WINDOWS
        run: |
          MAIN_FOLDER=`pwd`
          echo ${{ matrix.prefix }}
          CONDA_ENV_PATH=$CONDA/envs/ezc3d
          mkdir -p $BUILD_FOLDER
          cd $BUILD_FOLDER
  - cmd: cmake -G"Visual Studio 17 2022" -Ax64 -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_DOC=OFF -DBUILD_EXAMPLE=ON -DUSE_MATRIX_FAST_ACCESSOR=OFF -DBINDER_OCTAVE=OFF -DBINDER_PYTHON3=ON ..
          cmake --build . --config Release --target install -j${{ steps.cpu-cores.outputs.count }}
          cd $MAIN_FOLDER
        if: matrix.label == 'win-64'

      - name: Run tests WINDOWS
        run: |
          MAIN_FOLDER=`pwd`
          cd $MAIN_FOLDER/$BUILD_FOLDER/test
          cp Release/ezc3d_test.exe .
          ./ezc3d_test.exe
          cd $MAIN_FOLDER
        if: matrix.label == 'win-64'
    
